### ISSUE TITLE
Button "Mostrar" doesn't show placed items.

### ISSUE THREAD

**Issue by vlma98** [NeverDefineUs/vitaes#228]
Clicking on item does it, but button only switches text from "Mostrar" (show) to "Esconder" (hide) and vice-versa.
![Capturar](https://user-images.githubusercontent.com/26746899/54888128-1ca38a80-4e79-11e9-8393-50a6b71c4aa3.PNG)

**Comment by Arthurlpgc** [comment]
Hey, the intent of these buttons are to show or hide on the PDF, to edit you must click on the name, but knowing it is a bad UX, we are adding an 'Editar' Button to avoid confusion, does that answer your issue?
Thanks for reporting (:

**Comment by vlma98** [comment]
> Hey, the intent of these buttons are to show or hide on the PDF, to edit you must click on the name, but knowing it is a bad UX, we are adding an 'Editar' Button to avoid confusion, does that answer your issue?
> Thanks for reporting (:

Yess, thank you :)
