### ISSUE TITLE
Não consigo visualização os modelos (templates) de currículo 

### ISSUE THREAD

**Issue by jctvEC** [NeverDefineUs/vitaes#230]
Nessa página, https://vitaes.io/hub, ao clicar nos templates, mesmo logado como se pede quando quando não se está logado, não consigo ampliar a visualização dos templates.

![image](https://user-images.githubusercontent.com/26723995/54931673-3d5ef500-4ef8-11e9-97f0-31305be2fccb.png)

**Comment by RamonSaboya** [comment]
O template hub ainda está em desenvolvimento. Essa é uma funcionalidade que iremos adicionar ainda. Obrigado por reportar!

Fica o nosso convite para, se quiser contribuir, poderia ser uma boa forma de começar, implementando essa funcionalidade!

**Comment by Arthurlpgc** [comment]
Tem um pull request ajeitando esse issue ja, se quiser da uma olhada la (:
