### ISSUE TITLE
Special characters don't render correctly on some CV models

### ISSUE THREAD

**Issue by rafaelmotaalves** [NeverDefineUs/vitaes#331]
Special characters like "ç" and "é", don't get rendedered correctly in Modern CV and Software Engineer models.

**Comment by rafaelmotaalves** [comment]
* Modern CV
![WhatsApp Image 2019-05-19 at 14 24 58](https://user-images.githubusercontent.com/27863193/57987625-847de800-7a5a-11e9-9a0c-301d69c5f83d.jpeg)

* Software Engineer
![WhatsApp Image 2019-05-19 at 14 25 52](https://user-images.githubusercontent.com/27863193/57987629-9790b800-7a5a-11e9-85c9-6e387ce39023.jpeg)

**Comment by Arthurlpgc** [comment]
Modern CV happens only on specific areas apparently

**Comment by Arthurlpgc** [comment]
Trying to isolate it now
